//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.25 at 02:14:58 下午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sino.cn/webservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cn.easypeng.webservice;
